### ISSUE TITLE
Without a web.xml, this does not run

### ISSUE THREAD

**Issue by jeanbza** [geowarin/spring-mvc-examples#2]
```
jadekler at Jeans-MacBook-Pro in ~/workspace
$ java -jar jetty-runner.jar ~/workspace/spring-mvc-examples/mvc-base/target/mvc-base-1.0-SNAPSHOT.war
2015-02-15 21:14:59.164:INFO::Logging to StdErrLog::DEBUG=false via org.eclipse.jetty.util.log.StdErrLog
2015-02-15 21:14:59.165:INFO::Runner
2015-02-15 21:14:59.165:WARN::No tx manager found
2015-02-15 21:14:59.192:INFO::Deploying file:/Users/jadekler/workspace/spring-mvc-examples/mvc-base/target/mvc-base-1.0-SNAPSHOT.war @ /
[WebAppContext@7a07c5b4@7a07c5b4/,null,file:/Users/jadekler/workspace/spring-mvc-examples/mvc-base/target/mvc-base-1.0-SNAPSHOT.war]
2015-02-15 21:14:59.200:INFO::jetty-7.0.0.v20091005
2015-02-15 21:14:59.231:INFO::Extract jar:file:/Users/jadekler/workspace/spring-mvc-examples/mvc-base/target/mvc-base-1.0-SNAPSHOT.war!/ to /private/var/folders/15/r6j3mdp97p5247bkkj94p4v00000gn/T/Jetty_0_0_0_0_8080_mvc.base.1.0.SNAPSHOT.war____9hq7ao/webapp
2015-02-15 21:14:59.443:WARN::Failed startup of context WebAppContext@7a07c5b4@7a07c5b4/,file:/private/var/folders/15/r6j3mdp97p5247bkkj94p4v00000gn/T/Jetty_0_0_0_0_8080_mvc.base.1.0.SNAPSHOT.war____9hq7ao/webapp/,file:/Users/jadekler/workspace/spring-mvc-examples/mvc-base/target/mvc-base-1.0-SNAPSHOT.war
java.lang.NullPointerException
    at org.eclipse.jetty.webapp.WebXmlProcessor.parseFragment(WebXmlProcessor.java:316)
    at org.eclipse.jetty.webapp.FragmentConfiguration.parseWebFragments(FragmentConfiguration.java:93)
    at org.eclipse.jetty.webapp.FragmentConfiguration.preConfigure(FragmentConfiguration.java:47)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:339)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:164)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:164)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:92)
    at org.eclipse.jetty.server.Server.doStart(Server.java:232)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
    at org.mortbay.jetty.runner.Runner.run(Runner.java:448)
    at org.mortbay.jetty.runner.Runner.main(Runner.java:587)
2015-02-15 21:14:59.458:INFO::Started SelectChannelConnector@0.0.0.0:8080
^C2015-02-15 21:15:00.707:INFO::Shutdown hook executing
2015-02-15 21:15:00.778:INFO::Shutdown hook complete
```

**Comment by geowarin** [comment]
Hi @jadekler,

It looks more like a jetty problem. A servlet 3.0 container shouldn't force you to have a web.xml file.
What is this jetty-runner.jar? Do you have access to its source?
